name: Standalone builds

on:
  release:
    types: [created]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.0.1
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.x'
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install pyinstaller
      shell: bash
      run: python -m pip install pyinstaller
    - name: Write a standalone code
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: app.py
        contents: |
          import discodo.__main__
          if __name__ == "__main__":
              discodo.__main__.main()
        write-mode: overwrite
    - name: Build with pyinstaller
      shell: bash
      run: |
        pyinstaller -F --add-data "discodo/natives/bin/*;." ./app.py
    - name: Upload executable
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: dist/app.exe
        asset_name: discodo-win.exe
        asset_content_type: application/octet-stream

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.1
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.x'
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install pyinstaller
      shell: bash
      run: python -m pip install pyinstaller
    - name: Write a standalone code
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: app.py
        contents: |
          import discodo.__main__
          if __name__ == "__main__":
              discodo.__main__.main()
        write-mode: overwrite
    - name: Build with pyinstaller
      shell: bash
      run: |
        pyinstaller -F --add-data "discodo/natives/bin/*:." ./app.py
    - name: Upload executable
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: dist/app
        asset_name: discodo-linux
        asset_content_type: application/octet-stream

  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3.0.1
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.x'
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install pyinstaller
      shell: bash
      run: python -m pip install pyinstaller
    - name: Write a standalone code
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: app.py
        contents: |
          import discodo.__main__
          if __name__ == "__main__":
              discodo.__main__.main()
        write-mode: overwrite
    - name: Build with pyinstaller
      shell: bash
      run: |
        pyinstaller -F --add-data "discodo/natives/bin/*:." ./app.py
    - name: Upload executable
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: dist/app
        asset_name: discodo-mac
        asset_content_type: application/octet-stream
